// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdt0o96YBu2Mp8qpLkYOtmM88VK-ba_yc',
    appId: '1:569107488169:web:27c7ea1063d2055edcb8b8',
    messagingSenderId: '569107488169',
    projectId: 'listme-app',
    authDomain: 'listme-app.firebaseapp.com',
    storageBucket: 'listme-app.firebasestorage.app',
    measurementId: 'G-L7QJFSRFM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQtlbO5dlhQuRsA1QxPJBpvZ3xr3OPQwQ',
    appId: '1:569107488169:android:018122149c13f776dcb8b8',
    messagingSenderId: '569107488169',
    projectId: 'listme-app',
    storageBucket: 'listme-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALDPDmdeRPrs5CB5YN0zCJf6cfsm1rHzM',
    appId: '1:569107488169:ios:a155be118e61f768dcb8b8',
    messagingSenderId: '569107488169',
    projectId: 'listme-app',
    storageBucket: 'listme-app.firebasestorage.app',
    iosBundleId: 'com.example.listMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALDPDmdeRPrs5CB5YN0zCJf6cfsm1rHzM',
    appId: '1:569107488169:ios:a155be118e61f768dcb8b8',
    messagingSenderId: '569107488169',
    projectId: 'listme-app',
    storageBucket: 'listme-app.firebasestorage.app',
    iosBundleId: 'com.example.listMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdt0o96YBu2Mp8qpLkYOtmM88VK-ba_yc',
    appId: '1:569107488169:web:1d0555383245834bdcb8b8',
    messagingSenderId: '569107488169',
    projectId: 'listme-app',
    authDomain: 'listme-app.firebaseapp.com',
    storageBucket: 'listme-app.firebasestorage.app',
    measurementId: 'G-Q5HS4VYL1S',
  );
}
