name: Deploy Flutter Web to CasaOS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Web
        run: |
          flutter pub get
          flutter build web --release

      - name: Deploy to NAS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USER }}
          key: ${{ secrets.NAS_SSH_KEY }} # <-- REVISA QUE SE LLAME ASÍ EN GITHUB SECRETS
          port: ${{ secrets.NAS_PORT }}
          proxy_host: ${{ secrets.NAS_HOST }} # Usamos parámetros nativos de la v0.1.7
          proxy_username: ${{ secrets.NAS_USER }}
          proxy_key: ${{ secrets.NAS_SSH_KEY }}
          proxy_command: "cloudflared access ssh --hostname ${{ secrets.NAS_HOST }}"
          source: "build/web/*"
          target: "/DATA/AppData/flutter_web"
          strip_components: 2